# Generated by Django 2.1.7 on 2019-04-04 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('current_number', models.IntegerField(default=0)),
                ('managers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
